<?php
class Framework_Model_Db_PhpbbUsers extends Bull_Model_Abstract
{
     protected $table = "phpbb_users";

     protected $name  = "db";

     protected function postConstruct()      
     {
         $this->cols = array (
             'user_id' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_id',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => NULL,
                 'autoinc' => true,
                 'primary' => true,
             )),
             'user_type' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_type',
                 'type' => 'tinyint',
                 'size' => 2,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'group_id' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'group_id',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '3',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_permissions' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_permissions',
                 'type' => 'mediumtext',
                 'size' => NULL,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => NULL,
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_perm_from' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_perm_from',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_ip' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_ip',
                 'type' => 'varchar',
                 'size' => 40,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_regdate' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_regdate',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'username' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'username',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'username_clean' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'username_clean',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_password' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_password',
                 'type' => 'varchar',
                 'size' => 40,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_passchg' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_passchg',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_pass_convert' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_pass_convert',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_email' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_email',
                 'type' => 'varchar',
                 'size' => 100,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_email_hash' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_email_hash',
                 'type' => 'bigint',
                 'size' => 20,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_birthday' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_birthday',
                 'type' => 'varchar',
                 'size' => 10,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_lastvisit' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_lastvisit',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_lastmark' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_lastmark',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_lastpost_time' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_lastpost_time',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_lastpage' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_lastpage',
                 'type' => 'varchar',
                 'size' => 200,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_last_confirm_key' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_last_confirm_key',
                 'type' => 'varchar',
                 'size' => 10,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_last_search' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_last_search',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_warnings' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_warnings',
                 'type' => 'tinyint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_last_warning' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_last_warning',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_login_attempts' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_login_attempts',
                 'type' => 'tinyint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_inactive_reason' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_inactive_reason',
                 'type' => 'tinyint',
                 'size' => 2,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_inactive_time' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_inactive_time',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_posts' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_posts',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_lang' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_lang',
                 'type' => 'varchar',
                 'size' => 30,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_timezone' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_timezone',
                 'type' => 'decimal',
                 'size' => 5,
                 'scale' => 2,
                 'notnull' => true,
                 'default' => '0.00',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_dst' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_dst',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_dateformat' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_dateformat',
                 'type' => 'varchar',
                 'size' => 30,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => 'd M Y H:i',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_style' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_style',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_rank' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_rank',
                 'type' => 'mediumint',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_colour' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_colour',
                 'type' => 'varchar',
                 'size' => 6,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_new_privmsg' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_new_privmsg',
                 'type' => 'int',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_unread_privmsg' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_unread_privmsg',
                 'type' => 'int',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_last_privmsg' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_last_privmsg',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_message_rules' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_message_rules',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_full_folder' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_full_folder',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '-3',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_emailtime' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_emailtime',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_topic_show_days' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_topic_show_days',
                 'type' => 'smallint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_topic_sortby_type' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_topic_sortby_type',
                 'type' => 'varchar',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => 't',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_topic_sortby_dir' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_topic_sortby_dir',
                 'type' => 'varchar',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => 'd',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_post_show_days' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_post_show_days',
                 'type' => 'smallint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_post_sortby_type' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_post_sortby_type',
                 'type' => 'varchar',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => 't',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_post_sortby_dir' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_post_sortby_dir',
                 'type' => 'varchar',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => 'a',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_notify' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_notify',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_notify_pm' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_notify_pm',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_notify_type' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_notify_type',
                 'type' => 'tinyint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_allow_pm' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_allow_pm',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_allow_viewonline' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_allow_viewonline',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_allow_viewemail' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_allow_viewemail',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_allow_massemail' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_allow_massemail',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_options' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_options',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '230271',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_avatar' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_avatar',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_avatar_type' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_avatar_type',
                 'type' => 'tinyint',
                 'size' => 2,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_avatar_width' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_avatar_width',
                 'type' => 'smallint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_avatar_height' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_avatar_height',
                 'type' => 'smallint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_sig' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_sig',
                 'type' => 'mediumtext',
                 'size' => NULL,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => NULL,
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_sig_bbcode_uid' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_sig_bbcode_uid',
                 'type' => 'varchar',
                 'size' => 8,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_sig_bbcode_bitfield' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_sig_bbcode_bitfield',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_from' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_from',
                 'type' => 'varchar',
                 'size' => 100,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_icq' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_icq',
                 'type' => 'varchar',
                 'size' => 15,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_aim' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_aim',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_yim' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_yim',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_msnm' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_msnm',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_jabber' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_jabber',
                 'type' => 'varchar',
                 'size' => 255,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_website' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_website',
                 'type' => 'varchar',
                 'size' => 200,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_occ' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_occ',
                 'type' => 'text',
                 'size' => NULL,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => NULL,
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_interests' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_interests',
                 'type' => 'text',
                 'size' => NULL,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => NULL,
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_actkey' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_actkey',
                 'type' => 'varchar',
                 'size' => 32,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_newpasswd' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_newpasswd',
                 'type' => 'varchar',
                 'size' => 40,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_form_salt' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_form_salt',
                 'type' => 'varchar',
                 'size' => 32,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_new' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_new',
                 'type' => 'tinyint',
                 'size' => 1,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '1',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_reminded' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_reminded',
                 'type' => 'tinyint',
                 'size' => 4,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
             'user_reminded_time' => 
             Bull_Sql_Column::__set_state(array(
                 'name' => 'user_reminded_time',
                 'type' => 'int',
                 'size' => 11,
                 'scale' => NULL,
                 'notnull' => true,
                 'default' => '0',
                 'autoinc' => false,
                 'primary' => false,
             )),
         );
     }
}